/// <reference types="node" />
import Event from 'events';
import { callback } from "./Interfaces";
export declare class ControllerMachine extends Event {
    private Log;
    private mcp1;
    private mcp2;
    private goingTo;
    private motorState;
    private location;
    private sensorPiso;
    private receivingItem;
    private isDelivery;
    private isDispense;
    private enableMachine;
    private securityMachine;
    private currentProcess;
    constructor();
    private securityState;
    private initOuts;
    private initSensors;
    private resetSensors;
    closeSensors: (callback: any) => void;
    stopAll: () => void;
    private findElevator;
    private checkPosition;
    private motorStartDown;
    private motorStartUp;
    motorStop: () => void;
    motorCintaStart: (row: number, coll: number, coll2: number) => void;
    motorCintaStop: (row: number, coll: number, coll2: number) => void;
    private controlSensors;
    private manualController;
    private mainSignal;
    GoTo_old: (callback: any, row: number) => void;
    private elevatorEmpty;
    private prepareForDispense;
    private waitForRemoveItem;
    dispenseItem: (piso: number, c1: number, c2: number | null, height: number, callback: callback) => void;
    private findRow;
    private gotoInitPosition;
    private dispense;
    private testCeldas;
    private blokingType;
    private attempts;
    private readSensor;
    private controlTime;
    private controlBlocking;
    GoTo: (callback: any, row: number) => void;
}
